<?php

/**
 * Defines hook_block_info
 */
function pp_info_block_info()
{
  $blocks = [
    'pp_info' => [
      'info' => t('PP Info box'),
      'cache' => DRUPAL_CACHE_GLOBAL
    ],
    'pp_quarantine' => [
      'info' => t('PP quarantine box'),
      'cache' => DRUPAL_CACHE_GLOBAL
    ],
    'pp_vacation' => [
      'info' => t('PP vacation box'),
      'cache' => DRUPAL_CACHE_GLOBAL
    ],
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pp_info_block_view($delta = '')
{
  $block = [];

  switch ($delta) {
    // todo allow to edit content and type (high/low/info) and use render array
    case 'pp_info':
      $block['content'] = [
        '#markup' => '<div class="info-box info-box--high">
                        <p class="text">
                          <strong>Aktuálně:</strong>
                          <a href="/anti-covid-ochrana">Anti-COVID ochrana</a> - zakázková výroba čirých zábran a osobních štítů.
                          <a href="/anti-covid-ochrana">Zobrazit více.</a>
                        </p>
                      </div>',
      ];
      break;

    case 'pp_quarantine':
      $block['content'] = [
        '#markup' => '<div class="info-box info-box--low">
                        <p class="text">
                          Dle nařízení vlády ze dne 21.10.2020 je až do odvolání maloobchodní prodej uzavřen.
                        </p>
                      </div>',
      ];
      break;

    case 'pp_vacation':
      $block['content'] = [
        '#markup' => '<div class="info-box info-box--low">
                        <p class="text">
                          Ve dnech 16.8. až 20.8. je prodejna z důvodu dovolené uzavřena.
                        </p>
                      </div>',
      ];
      break;
  }

  return $block;
}


