<?php

/**
 * Defines hook_block_info
 */
function pp_info_block_info()
{
  $blocks = [
    'pp_info' => [
      'info' => t('PP Info box'),
      'cache' => DRUPAL_CACHE_GLOBAL
    ]
  ];

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pp_info_block_view($delta = '')
{
  $block = [];

  switch ($delta) {
    // todo allow to edit content and type (high/low/info) and use render array
    case 'pp_info':
      $block['content'] = [
        '#markup' => '<div class="info-box info-box--high">
                        <p class="text">
                          <strong>Aktuálně:</strong>
                          <a href="/anti-covid-ochrana">Anti-COVID ochrana</a> - zakázková výroba čirých zábran a osobních štítů.
                          <a href="/anti-covid-ochrana">Zobrazit více.</a>
                        </p>
                      </div>',
      ];
  }

  return $block;
}


