<?php

/**
 * Defines hook_block_info
 */
function pp_base_block_info() {
  $blocks = [
    'pp_products' => [
      'info' => t('Produkty'),
      'cache' => DRUPAL_CACHE_GLOBAL
    ]
  ];

  return $blocks;
}


function pp_base_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'pp_products':
      $block['content'] = [
        '#theme' => 'pp_products',
        '#items' => [
          [
            'title' => 'Deskové materiály',
            'description' => ['Polykarbonátové desky plné i komůrkové, plexisklo, technické plasty a další typy materiálů.'],
            'path' => 'produkty/deskove_materialy',
            'img' => '/sites/default/files/products-01-2x.jpg'
          ],
          [
            'title' => 'PVC',
            'description' => ['Lamelové clony', 'Kyvná vrata'],
            'path' => 'produkty/pvc',
            'img' => '/sites/default/files/products-02-2x.jpg'
          ],
          [
            'title' => 'Lepidla',
            'description' => ['Dvojsložková lepidla vhodná pro průmyslové použití.'],
            'path' => 'produkty/lepidla',
            'img' => '/sites/default/files/lepidla_0.jpg'
          ],
        ],
      ];
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function pp_base_theme($existing, $type, $theme, $path) {
  return [
    'pp_products' => [
      'template' => 'templates/pp_products',
      'variables' => [
        'items' => []
      ]
    ]
  ];
}
